name:       'CSE 440'

brandimage: ''
brandtext:  'CSE 440 - Introduction to HCI - Spring 2016'

lessc: node_modules/.bin/lessc

navbar:
  items:
    - text: 'Home'
      link: 'index.html'
    - text: 'Projects'
      link: 'projects.html'
    - text: 'Calendar'
      link: 'calendar.html'

exclude:
  # Bootstrap
  - bootstrap/less
  # CSS/LESS files, these are all included by css/base/styles.less
  - css/styles.less
  - css/base/bar.less
  - css/base/base.less
  - css/base/syntax.css
  # Node
  - node_modules
  - npm-shrinkwrap.json
  - package.json
  # Python
  - env34
  - env35
  - requirements3.in
  - requirements3.txt
  - tasks.py
  - tasks.pyc
  # README
  - README.md
  # Ruby
  - Gemfile
  - Gemfile.lock
  # Tests
  - tests

collections:
  assignments:
    output: true
  projects:
    output: true
